// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: com/coralogix/alerts/v1/tracing_alert.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TracingAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionLatency uint32        `protobuf:"varint,1,opt,name=condition_latency,json=conditionLatency,proto3" json:"condition_latency,omitempty"`
	FieldFilters     []*FilterData `protobuf:"bytes,2,rep,name=field_filters,json=fieldFilters,proto3" json:"field_filters,omitempty"`
	TagFilters       []*FilterData `protobuf:"bytes,3,rep,name=tag_filters,json=tagFilters,proto3" json:"tag_filters,omitempty"`
}

func (x *TracingAlert) Reset() {
	*x = TracingAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TracingAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracingAlert) ProtoMessage() {}

func (x *TracingAlert) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracingAlert.ProtoReflect.Descriptor instead.
func (*TracingAlert) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescGZIP(), []int{0}
}

func (x *TracingAlert) GetConditionLatency() uint32 {
	if x != nil {
		return x.ConditionLatency
	}
	return 0
}

func (x *TracingAlert) GetFieldFilters() []*FilterData {
	if x != nil {
		return x.FieldFilters
	}
	return nil
}

func (x *TracingAlert) GetTagFilters() []*FilterData {
	if x != nil {
		return x.TagFilters
	}
	return nil
}

type FilterData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field   string     `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Filters []*Filters `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *FilterData) Reset() {
	*x = FilterData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterData) ProtoMessage() {}

func (x *FilterData) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterData.ProtoReflect.Descriptor instead.
func (*FilterData) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescGZIP(), []int{1}
}

func (x *FilterData) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterData) GetFilters() []*Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Filters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values   []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Operator string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (x *Filters) Reset() {
	*x = Filters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescGZIP(), []int{2}
}

func (x *Filters) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Filters) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

var File_com_coralogix_alerts_v1_tracing_alert_proto protoreflect.FileDescriptor

var file_com_coralogix_alerts_v1_tracing_alert_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xcb, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63, 0x69,
	0x6e, 0x67, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x48, 0x0a, 0x0d, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0c, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x44,
	0x0a, 0x0b, 0x74, 0x61, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f,
	0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x74, 0x61, 0x67, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x5e, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x22, 0x3d, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescOnce sync.Once
	file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescData = file_com_coralogix_alerts_v1_tracing_alert_proto_rawDesc
)

func file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescGZIP() []byte {
	file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescOnce.Do(func() {
		file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescData)
	})
	return file_com_coralogix_alerts_v1_tracing_alert_proto_rawDescData
}

var file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_com_coralogix_alerts_v1_tracing_alert_proto_goTypes = []interface{}{
	(*TracingAlert)(nil), // 0: com.coralogix.alerts.v1.TracingAlert
	(*FilterData)(nil),   // 1: com.coralogix.alerts.v1.FilterData
	(*Filters)(nil),      // 2: com.coralogix.alerts.v1.Filters
}
var file_com_coralogix_alerts_v1_tracing_alert_proto_depIdxs = []int32{
	1, // 0: com.coralogix.alerts.v1.TracingAlert.field_filters:type_name -> com.coralogix.alerts.v1.FilterData
	1, // 1: com.coralogix.alerts.v1.TracingAlert.tag_filters:type_name -> com.coralogix.alerts.v1.FilterData
	2, // 2: com.coralogix.alerts.v1.FilterData.filters:type_name -> com.coralogix.alerts.v1.Filters
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_com_coralogix_alerts_v1_tracing_alert_proto_init() }
func file_com_coralogix_alerts_v1_tracing_alert_proto_init() {
	if File_com_coralogix_alerts_v1_tracing_alert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TracingAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_coralogix_alerts_v1_tracing_alert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_coralogix_alerts_v1_tracing_alert_proto_goTypes,
		DependencyIndexes: file_com_coralogix_alerts_v1_tracing_alert_proto_depIdxs,
		MessageInfos:      file_com_coralogix_alerts_v1_tracing_alert_proto_msgTypes,
	}.Build()
	File_com_coralogix_alerts_v1_tracing_alert_proto = out.File
	file_com_coralogix_alerts_v1_tracing_alert_proto_rawDesc = nil
	file_com_coralogix_alerts_v1_tracing_alert_proto_goTypes = nil
	file_com_coralogix_alerts_v1_tracing_alert_proto_depIdxs = nil
}
