// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: com/coralogixapis/dashboards/v1/ast/filter.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source    *Filter_Source        `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Enabled   *wrapperspb.BoolValue `protobuf:"bytes,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Collapsed *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetSource() *Filter_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Filter) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Filter) GetCollapsed() *wrapperspb.BoolValue {
	if x != nil {
		return x.Collapsed
	}
	return nil
}

type Filter_Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Filter_Source_Logs
	Value isFilter_Source_Value `protobuf_oneof:"value"`
}

func (x *Filter_Source) Reset() {
	*x = Filter_Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Source) ProtoMessage() {}

func (x *Filter_Source) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Source.ProtoReflect.Descriptor instead.
func (*Filter_Source) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Filter_Source) GetValue() isFilter_Source_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Filter_Source) GetLogs() *Filter_LogFilter {
	if x, ok := x.GetValue().(*Filter_Source_Logs); ok {
		return x.Logs
	}
	return nil
}

type isFilter_Source_Value interface {
	isFilter_Source_Value()
}

type Filter_Source_Logs struct {
	Logs *Filter_LogFilter `protobuf:"bytes,1,opt,name=logs,proto3,oneof"`
}

func (*Filter_Source_Logs) isFilter_Source_Value() {}

type Filter_LogFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field    *wrapperspb.StringValue    `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator *Filter_LogFilter_Operator `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (x *Filter_LogFilter) Reset() {
	*x = Filter_LogFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_LogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_LogFilter) ProtoMessage() {}

func (x *Filter_LogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_LogFilter.ProtoReflect.Descriptor instead.
func (*Filter_LogFilter) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Filter_LogFilter) GetField() *wrapperspb.StringValue {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Filter_LogFilter) GetOperator() *Filter_LogFilter_Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type Filter_Equals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Filter_Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *Filter_Equals) Reset() {
	*x = Filter_Equals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Equals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Equals) ProtoMessage() {}

func (x *Filter_Equals) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Equals.ProtoReflect.Descriptor instead.
func (*Filter_Equals) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Filter_Equals) GetSelection() *Filter_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type Filter_Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Filter_Selection_All
	//	*Filter_Selection_List
	Value isFilter_Selection_Value `protobuf_oneof:"value"`
}

func (x *Filter_Selection) Reset() {
	*x = Filter_Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Selection) ProtoMessage() {}

func (x *Filter_Selection) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Selection.ProtoReflect.Descriptor instead.
func (*Filter_Selection) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 3}
}

func (m *Filter_Selection) GetValue() isFilter_Selection_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Filter_Selection) GetAll() *Filter_Selection_AllSelection {
	if x, ok := x.GetValue().(*Filter_Selection_All); ok {
		return x.All
	}
	return nil
}

func (x *Filter_Selection) GetList() *Filter_Selection_ListSelection {
	if x, ok := x.GetValue().(*Filter_Selection_List); ok {
		return x.List
	}
	return nil
}

type isFilter_Selection_Value interface {
	isFilter_Selection_Value()
}

type Filter_Selection_All struct {
	All *Filter_Selection_AllSelection `protobuf:"bytes,1,opt,name=all,proto3,oneof"`
}

type Filter_Selection_List struct {
	List *Filter_Selection_ListSelection `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

func (*Filter_Selection_All) isFilter_Selection_Value() {}

func (*Filter_Selection_List) isFilter_Selection_Value() {}

type Filter_LogFilter_Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Filter_LogFilter_Operator_Equals
	Value isFilter_LogFilter_Operator_Value `protobuf_oneof:"value"`
}

func (x *Filter_LogFilter_Operator) Reset() {
	*x = Filter_LogFilter_Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_LogFilter_Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_LogFilter_Operator) ProtoMessage() {}

func (x *Filter_LogFilter_Operator) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_LogFilter_Operator.ProtoReflect.Descriptor instead.
func (*Filter_LogFilter_Operator) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (m *Filter_LogFilter_Operator) GetValue() isFilter_LogFilter_Operator_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Filter_LogFilter_Operator) GetEquals() *Filter_Equals {
	if x, ok := x.GetValue().(*Filter_LogFilter_Operator_Equals); ok {
		return x.Equals
	}
	return nil
}

type isFilter_LogFilter_Operator_Value interface {
	isFilter_LogFilter_Operator_Value()
}

type Filter_LogFilter_Operator_Equals struct {
	Equals *Filter_Equals `protobuf:"bytes,1,opt,name=equals,proto3,oneof"`
}

func (*Filter_LogFilter_Operator_Equals) isFilter_LogFilter_Operator_Value() {}

type Filter_Selection_AllSelection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Filter_Selection_AllSelection) Reset() {
	*x = Filter_Selection_AllSelection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Selection_AllSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Selection_AllSelection) ProtoMessage() {}

func (x *Filter_Selection_AllSelection) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Selection_AllSelection.ProtoReflect.Descriptor instead.
func (*Filter_Selection_AllSelection) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 3, 0}
}

type Filter_Selection_ListSelection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Filter_Selection_ListSelection) Reset() {
	*x = Filter_Selection_ListSelection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter_Selection_ListSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter_Selection_ListSelection) ProtoMessage() {}

func (x *Filter_Selection_ListSelection) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter_Selection_ListSelection.ProtoReflect.Descriptor instead.
func (*Filter_Selection_ListSelection) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *Filter_Selection_ListSelection) GetValues() []*wrapperspb.StringValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_com_coralogixapis_dashboards_v1_ast_filter_proto protoreflect.FileDescriptor

var file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDesc = []byte{
	0x0a, 0x30, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x73, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69,
	0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x07, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x4a, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67,
	0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x34,
	0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x70, 0x73, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x09, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x1a, 0x5e,
	0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72,
	0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x04, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xfe,
	0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x5a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67,
	0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x4c, 0x6f, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x61, 0x0a, 0x08,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73,
	0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x5d, 0x0a, 0x06, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x53, 0x0a, 0x09, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61,
	0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x9e,
	0x02, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x03,
	0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x03, 0x61, 0x6c, 0x6c, 0x12, 0x59, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x43, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67,
	0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a,
	0x0e, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x45, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x34, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescOnce sync.Once
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescData = file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDesc
)

func file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescGZIP() []byte {
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescOnce.Do(func() {
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescData)
	})
	return file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDescData
}

var file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_com_coralogixapis_dashboards_v1_ast_filter_proto_goTypes = []interface{}{
	(*Filter)(nil),                         // 0: com.coralogixapis.dashboards.v1.ast.Filter
	(*Filter_Source)(nil),                  // 1: com.coralogixapis.dashboards.v1.ast.Filter.Source
	(*Filter_LogFilter)(nil),               // 2: com.coralogixapis.dashboards.v1.ast.Filter.LogFilter
	(*Filter_Equals)(nil),                  // 3: com.coralogixapis.dashboards.v1.ast.Filter.Equals
	(*Filter_Selection)(nil),               // 4: com.coralogixapis.dashboards.v1.ast.Filter.Selection
	(*Filter_LogFilter_Operator)(nil),      // 5: com.coralogixapis.dashboards.v1.ast.Filter.LogFilter.Operator
	(*Filter_Selection_AllSelection)(nil),  // 6: com.coralogixapis.dashboards.v1.ast.Filter.Selection.AllSelection
	(*Filter_Selection_ListSelection)(nil), // 7: com.coralogixapis.dashboards.v1.ast.Filter.Selection.ListSelection
	(*wrapperspb.BoolValue)(nil),           // 8: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil),         // 9: google.protobuf.StringValue
}
var file_com_coralogixapis_dashboards_v1_ast_filter_proto_depIdxs = []int32{
	1,  // 0: com.coralogixapis.dashboards.v1.ast.Filter.source:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.Source
	8,  // 1: com.coralogixapis.dashboards.v1.ast.Filter.enabled:type_name -> google.protobuf.BoolValue
	8,  // 2: com.coralogixapis.dashboards.v1.ast.Filter.collapsed:type_name -> google.protobuf.BoolValue
	2,  // 3: com.coralogixapis.dashboards.v1.ast.Filter.Source.logs:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.LogFilter
	9,  // 4: com.coralogixapis.dashboards.v1.ast.Filter.LogFilter.field:type_name -> google.protobuf.StringValue
	5,  // 5: com.coralogixapis.dashboards.v1.ast.Filter.LogFilter.operator:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.LogFilter.Operator
	4,  // 6: com.coralogixapis.dashboards.v1.ast.Filter.Equals.selection:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.Selection
	6,  // 7: com.coralogixapis.dashboards.v1.ast.Filter.Selection.all:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.Selection.AllSelection
	7,  // 8: com.coralogixapis.dashboards.v1.ast.Filter.Selection.list:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.Selection.ListSelection
	3,  // 9: com.coralogixapis.dashboards.v1.ast.Filter.LogFilter.Operator.equals:type_name -> com.coralogixapis.dashboards.v1.ast.Filter.Equals
	9,  // 10: com.coralogixapis.dashboards.v1.ast.Filter.Selection.ListSelection.values:type_name -> google.protobuf.StringValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_com_coralogixapis_dashboards_v1_ast_filter_proto_init() }
func file_com_coralogixapis_dashboards_v1_ast_filter_proto_init() {
	if File_com_coralogixapis_dashboards_v1_ast_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_LogFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Equals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_LogFilter_Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Selection_AllSelection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter_Selection_ListSelection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Filter_Source_Logs)(nil),
	}
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Filter_Selection_All)(nil),
		(*Filter_Selection_List)(nil),
	}
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Filter_LogFilter_Operator_Equals)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_coralogixapis_dashboards_v1_ast_filter_proto_goTypes,
		DependencyIndexes: file_com_coralogixapis_dashboards_v1_ast_filter_proto_depIdxs,
		MessageInfos:      file_com_coralogixapis_dashboards_v1_ast_filter_proto_msgTypes,
	}.Build()
	File_com_coralogixapis_dashboards_v1_ast_filter_proto = out.File
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_rawDesc = nil
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_goTypes = nil
	file_com_coralogixapis_dashboards_v1_ast_filter_proto_depIdxs = nil
}
