// Code generated by coralogix-iac-codegen v0.1.0-beta.19. DO NOT EDIT.

package customthing

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"example.com/iac-test-sdk/go/openapi/gen/custom_things_service"
)

// tfData is a tfsdk.Config, tfsdk.Plan, or tfsdk.State.
type tfData interface {
	Get(ctx context.Context, target interface{}) diag.Diagnostics
	GetAttribute(ctx context.Context, p path.Path, target interface{}) diag.Diagnostics
}

// updateFields are the Terraform attributes of the Update fields, in model
// order.
var updateFields = []struct {
	attr          string
	serverDefault bool
}{
	{attr: "name", serverDefault: false},
	{attr: "origin", serverDefault: false},
	{attr: "notes", serverDefault: false},
	{attr: "attachment", serverDefault: false},
	{attr: "condition", serverDefault: false},
}

// updateChanged reports whether an Update field has a different value in the
// plan and in the state. It uses Terraform equality, so the order of a Set
// does not matter.
func updateChanged(ctx context.Context, config, plan, state tfData) (bool, diag.Diagnostics) {
	var diags diag.Diagnostics
	changed := false
	for _, field := range updateFields {
		var c, p, s attr.Value
		var fieldDiags diag.Diagnostics
		fieldDiags.Append(config.GetAttribute(ctx, path.Root(field.attr), &c)...)
		fieldDiags.Append(plan.GetAttribute(ctx, path.Root(field.attr), &p)...)
		fieldDiags.Append(state.GetAttribute(ctx, path.Root(field.attr), &s)...)
		diags.Append(fieldDiags...)
		if fieldDiags.HasError() {
			continue
		}
		validateRequestValue(path.Root(field.attr), c, p, field.serverDefault, &diags)
		if !p.Equal(s) {
			changed = true
		}
	}
	return changed, diags
}

// updateRequest returns the Update body of the plan. The Update is a full
// replace (PUT), so the body has every Update field, and it has no update
// mask. A value that the plan clears (null) is not in the body, and the
// server clears it. updateRequest returns nil when no Update field changed.
// Then the caller sends no request (D14).
func updateRequest(ctx context.Context, config, plan, state tfData) (*custom_things_service.ReplaceCustomThingRequest, diag.Diagnostics) {
	changed, diags := updateChanged(ctx, config, plan, state)
	if diags.HasError() || !changed {
		return nil, diags
	}
	var m CustomThingModel
	diags.Append(plan.Get(ctx, &m)...)
	if diags.HasError() {
		return nil, diags
	}
	body, d := expandUpdate(ctx, &m)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return body, diags
}
