// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: com/coralogix/alerts/v2/alert_notification_group.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyOn int32

const (
	NotifyOn_TRIGGERED_ONLY         NotifyOn = 0
	NotifyOn_TRIGGERED_AND_RESOLVED NotifyOn = 1
)

// Enum value maps for NotifyOn.
var (
	NotifyOn_name = map[int32]string{
		0: "TRIGGERED_ONLY",
		1: "TRIGGERED_AND_RESOLVED",
	}
	NotifyOn_value = map[string]int32{
		"TRIGGERED_ONLY":         0,
		"TRIGGERED_AND_RESOLVED": 1,
	}
)

func (x NotifyOn) Enum() *NotifyOn {
	p := new(NotifyOn)
	*p = x
	return p
}

func (x NotifyOn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyOn) Descriptor() protoreflect.EnumDescriptor {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_enumTypes[0].Descriptor()
}

func (NotifyOn) Type() protoreflect.EnumType {
	return &file_com_coralogix_alerts_v2_alert_notification_group_proto_enumTypes[0]
}

func (x NotifyOn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyOn.Descriptor instead.
func (NotifyOn) EnumDescriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP(), []int{0}
}

type ShowInInsight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetriggeringPeriodSeconds *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=retriggering_period_seconds,json=retriggeringPeriodSeconds,proto3,oneof" json:"retriggering_period_seconds,omitempty"`
	NotifyOn                  *NotifyOn               `protobuf:"varint,2,opt,name=notify_on,json=notifyOn,proto3,enum=com.coralogix.alerts.v2.NotifyOn,oneof" json:"notify_on,omitempty"`
}

func (x *ShowInInsight) Reset() {
	*x = ShowInInsight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowInInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowInInsight) ProtoMessage() {}

func (x *ShowInInsight) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowInInsight.ProtoReflect.Descriptor instead.
func (*ShowInInsight) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP(), []int{0}
}

func (x *ShowInInsight) GetRetriggeringPeriodSeconds() *wrapperspb.UInt32Value {
	if x != nil {
		return x.RetriggeringPeriodSeconds
	}
	return nil
}

func (x *ShowInInsight) GetNotifyOn() NotifyOn {
	if x != nil && x.NotifyOn != nil {
		return *x.NotifyOn
	}
	return NotifyOn_TRIGGERED_ONLY
}

type AlertNotificationGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupByFields []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=group_by_fields,json=groupByFields,proto3" json:"group_by_fields,omitempty"`
	Notifications []*AlertNotification      `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications,omitempty"`
}

func (x *AlertNotificationGroups) Reset() {
	*x = AlertNotificationGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertNotificationGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNotificationGroups) ProtoMessage() {}

func (x *AlertNotificationGroups) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNotificationGroups.ProtoReflect.Descriptor instead.
func (*AlertNotificationGroups) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP(), []int{1}
}

func (x *AlertNotificationGroups) GetGroupByFields() []*wrapperspb.StringValue {
	if x != nil {
		return x.GroupByFields
	}
	return nil
}

func (x *AlertNotificationGroups) GetNotifications() []*AlertNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type AlertNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetriggeringPeriodSeconds *wrapperspb.UInt32Value `protobuf:"bytes,1,opt,name=retriggering_period_seconds,json=retriggeringPeriodSeconds,proto3,oneof" json:"retriggering_period_seconds,omitempty"`
	NotifyOn                  *NotifyOn               `protobuf:"varint,2,opt,name=notify_on,json=notifyOn,proto3,enum=com.coralogix.alerts.v2.NotifyOn,oneof" json:"notify_on,omitempty"`
	// Types that are assignable to IntegrationType:
	//	*AlertNotification_IntegrationId
	//	*AlertNotification_Recipients
	IntegrationType isAlertNotification_IntegrationType `protobuf_oneof:"integration_type"`
}

func (x *AlertNotification) Reset() {
	*x = AlertNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNotification) ProtoMessage() {}

func (x *AlertNotification) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNotification.ProtoReflect.Descriptor instead.
func (*AlertNotification) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP(), []int{2}
}

func (x *AlertNotification) GetRetriggeringPeriodSeconds() *wrapperspb.UInt32Value {
	if x != nil {
		return x.RetriggeringPeriodSeconds
	}
	return nil
}

func (x *AlertNotification) GetNotifyOn() NotifyOn {
	if x != nil && x.NotifyOn != nil {
		return *x.NotifyOn
	}
	return NotifyOn_TRIGGERED_ONLY
}

func (m *AlertNotification) GetIntegrationType() isAlertNotification_IntegrationType {
	if m != nil {
		return m.IntegrationType
	}
	return nil
}

func (x *AlertNotification) GetIntegrationId() *wrapperspb.UInt32Value {
	if x, ok := x.GetIntegrationType().(*AlertNotification_IntegrationId); ok {
		return x.IntegrationId
	}
	return nil
}

func (x *AlertNotification) GetRecipients() *Recipients {
	if x, ok := x.GetIntegrationType().(*AlertNotification_Recipients); ok {
		return x.Recipients
	}
	return nil
}

type isAlertNotification_IntegrationType interface {
	isAlertNotification_IntegrationType()
}

type AlertNotification_IntegrationId struct {
	IntegrationId *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=integration_id,json=integrationId,proto3,oneof"`
}

type AlertNotification_Recipients struct {
	Recipients *Recipients `protobuf:"bytes,5,opt,name=recipients,proto3,oneof"`
}

func (*AlertNotification_IntegrationId) isAlertNotification_IntegrationType() {}

func (*AlertNotification_Recipients) isAlertNotification_IntegrationType() {}

type Recipients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *Recipients) Reset() {
	*x = Recipients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipients) ProtoMessage() {}

func (x *Recipients) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipients.ProtoReflect.Descriptor instead.
func (*Recipients) Descriptor() ([]byte, []int) {
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP(), []int{3}
}

func (x *Recipients) GetEmails() []*wrapperspb.StringValue {
	if x != nil {
		return x.Emails
	}
	return nil
}

var File_com_coralogix_alerts_v2_alert_notification_group_proto protoreflect.FileDescriptor

var file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDesc = []byte{
	0x0a, 0x36, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f,
	0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x76,
	0x32, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x49, 0x6e, 0x73, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x61, 0x0a, 0x1b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x19, 0x72, 0x65, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x88, 0x01, 0x01, 0x12, 0x43, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5f, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4f, 0x6e, 0x48, 0x01, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x1e, 0x0a, 0x1c, 0x5f,
	0x72, 0x65, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6f, 0x6e, 0x22, 0xb1, 0x01, 0x0a, 0x17, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x44, 0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62,
	0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x50, 0x0a, 0x0d, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67,
	0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x8b, 0x03,
	0x0a, 0x11, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x61, 0x0a, 0x1b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x01, 0x52, 0x19, 0x72, 0x65, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x88, 0x01, 0x01, 0x12, 0x43, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5f, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4f, 0x6e, 0x48, 0x02, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x45, 0x0a, 0x0e, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x45, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x72,
	0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x76, 0x32,
	0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x12, 0x0a, 0x10, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x1e, 0x0a,
	0x1c, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0a, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2a,
	0x3a, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x54,
	0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x45, 0x44, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x54, 0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x45, 0x44, 0x5f, 0x41, 0x4e, 0x44,
	0x5f, 0x52, 0x45, 0x53, 0x4f, 0x4c, 0x56, 0x45, 0x44, 0x10, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescOnce sync.Once
	file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescData = file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDesc
)

func file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescGZIP() []byte {
	file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescOnce.Do(func() {
		file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescData)
	})
	return file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDescData
}

var file_com_coralogix_alerts_v2_alert_notification_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_com_coralogix_alerts_v2_alert_notification_group_proto_goTypes = []interface{}{
	(NotifyOn)(0),                   // 0: com.coralogix.alerts.v2.NotifyOn
	(*ShowInInsight)(nil),           // 1: com.coralogix.alerts.v2.ShowInInsight
	(*AlertNotificationGroups)(nil), // 2: com.coralogix.alerts.v2.AlertNotificationGroups
	(*AlertNotification)(nil),       // 3: com.coralogix.alerts.v2.AlertNotification
	(*Recipients)(nil),              // 4: com.coralogix.alerts.v2.Recipients
	(*wrapperspb.UInt32Value)(nil),  // 5: google.protobuf.UInt32Value
	(*wrapperspb.StringValue)(nil),  // 6: google.protobuf.StringValue
}
var file_com_coralogix_alerts_v2_alert_notification_group_proto_depIdxs = []int32{
	5, // 0: com.coralogix.alerts.v2.ShowInInsight.retriggering_period_seconds:type_name -> google.protobuf.UInt32Value
	0, // 1: com.coralogix.alerts.v2.ShowInInsight.notify_on:type_name -> com.coralogix.alerts.v2.NotifyOn
	6, // 2: com.coralogix.alerts.v2.AlertNotificationGroups.group_by_fields:type_name -> google.protobuf.StringValue
	3, // 3: com.coralogix.alerts.v2.AlertNotificationGroups.notifications:type_name -> com.coralogix.alerts.v2.AlertNotification
	5, // 4: com.coralogix.alerts.v2.AlertNotification.retriggering_period_seconds:type_name -> google.protobuf.UInt32Value
	0, // 5: com.coralogix.alerts.v2.AlertNotification.notify_on:type_name -> com.coralogix.alerts.v2.NotifyOn
	5, // 6: com.coralogix.alerts.v2.AlertNotification.integration_id:type_name -> google.protobuf.UInt32Value
	4, // 7: com.coralogix.alerts.v2.AlertNotification.recipients:type_name -> com.coralogix.alerts.v2.Recipients
	6, // 8: com.coralogix.alerts.v2.Recipients.emails:type_name -> google.protobuf.StringValue
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_com_coralogix_alerts_v2_alert_notification_group_proto_init() }
func file_com_coralogix_alerts_v2_alert_notification_group_proto_init() {
	if File_com_coralogix_alerts_v2_alert_notification_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowInInsight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertNotificationGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AlertNotification_IntegrationId)(nil),
		(*AlertNotification_Recipients)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_coralogix_alerts_v2_alert_notification_group_proto_goTypes,
		DependencyIndexes: file_com_coralogix_alerts_v2_alert_notification_group_proto_depIdxs,
		EnumInfos:         file_com_coralogix_alerts_v2_alert_notification_group_proto_enumTypes,
		MessageInfos:      file_com_coralogix_alerts_v2_alert_notification_group_proto_msgTypes,
	}.Build()
	File_com_coralogix_alerts_v2_alert_notification_group_proto = out.File
	file_com_coralogix_alerts_v2_alert_notification_group_proto_rawDesc = nil
	file_com_coralogix_alerts_v2_alert_notification_group_proto_goTypes = nil
	file_com_coralogix_alerts_v2_alert_notification_group_proto_depIdxs = nil
}
