package generator

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/coralogix/terraform-provider-coralogix/tools/iac-codegen/internal/acceptance"
	"github.com/coralogix/terraform-provider-coralogix/tools/iac-codegen/internal/overrides"
)

var renamePath = os.Rename

func publish(output string, files map[string][]byte) error {
	abs, err := filepath.Abs(output)
	if err != nil {
		return fmt.Errorf("resolve output directory: %w", err)
	}
	if abs == string(filepath.Separator) || filepath.Base(abs) == "." {
		return fmt.Errorf("refuse broad output directory %s", abs)
	}
	parent := filepath.Dir(abs)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return fmt.Errorf("create output parent: %w", err)
	}
	if err := checkOwned(abs); err != nil {
		return err
	}
	stage, err := stageOutput(parent, abs, files)
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(stage) }()
	return replaceOutput(abs, parent, stage)
}

func stageOutput(parent, output string, files map[string][]byte) (string, error) {
	stage, err := os.MkdirTemp(parent, "."+filepath.Base(output)+".stage-")
	if err != nil {
		return "", fmt.Errorf("create staged output: %w", err)
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		if filepath.Base(name) != name || filepath.Ext(name) != ".go" && !inputFile(name) {
			_ = os.RemoveAll(stage)
			return "", fmt.Errorf("invalid generated file name %q", name)
		}
		if err := os.WriteFile(filepath.Join(stage, name), files[name], 0o644); err != nil {
			_ = os.RemoveAll(stage)
			return "", fmt.Errorf("write staged %s: %w", name, err)
		}
	}
	return stage, nil
}

func replaceOutput(output, parent, stage string) error {
	backup := ""
	if _, err := os.Lstat(output); err == nil {
		backup, err = os.MkdirTemp(parent, "."+filepath.Base(output)+".backup-")
		if err != nil {
			return fmt.Errorf("reserve output backup: %w", err)
		}
		if err := os.Remove(backup); err != nil {
			return fmt.Errorf("reserve output backup: %w", err)
		}
		if err := renamePath(output, backup); err != nil {
			return fmt.Errorf("move previous output to backup: %w", err)
		}
	}
	if err := renamePath(stage, output); err != nil {
		if backup != "" {
			if restoreErr := renamePath(backup, output); restoreErr != nil {
				return errors.Join(fmt.Errorf("publish staged output: %w", err), fmt.Errorf("restore previous output: %w", restoreErr))
			}
		}
		return fmt.Errorf("publish staged output: %w", err)
	}
	if backup != "" {
		if err := os.RemoveAll(backup); err != nil {
			return fmt.Errorf("remove previous generated output backup %s: %w", backup, err)
		}
	}
	return nil
}

func checkOwned(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect output directory: %w", err)
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("output %s exists but is not a generator-owned directory", path)
	}
	entries, err := os.ReadDir(path)
	if err != nil {
		return fmt.Errorf("read output directory: %w", err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("output %s exists but is not generator-owned", path)
	}
	for _, entry := range entries {
		if inputFile(entry.Name()) && !entry.IsDir() {
			continue // the one file that people write; publish keeps it
		}
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" || strings.Contains(entry.Name(), string(filepath.Separator)) {
			return fmt.Errorf("output %s is not generator-owned: unexpected entry %s", path, entry.Name())
		}
		data, err := os.ReadFile(filepath.Join(path, entry.Name()))
		if err != nil {
			return fmt.Errorf("inspect generated file %s: %w", entry.Name(), err)
		}
		line, _, _ := bytes.Cut(data, []byte("\n"))
		if !bytes.HasPrefix(line, []byte("// Code generated by coralogix-iac-codegen v")) || !bytes.HasSuffix(line, []byte(". DO NOT EDIT.")) {
			return fmt.Errorf("output %s is not generator-owned: %s lacks a valid generator header", path, entry.Name())
		}
	}
	return nil
}

// inputFile reports whether the name is a file that people write and that the generator reads.
// Publish keeps these files.
func inputFile(name string) bool {
	return name == overrides.FileName || name == acceptance.FileName
}
