// Code generated by coralogix-iac-codegen v0.1.0-beta.19. DO NOT EDIT.

package wrapthing

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"example.com/iac-test-sdk/go/openapi/cxsdk"
	"example.com/iac-test-sdk/go/openapi/gen/wrap_things_service"
	"github.com/coralogix/terraform-provider-coralogix/internal/clientset"
)

// TypeName is the resource type name without the provider prefix.
const TypeName = "wrap_thing"

var (
	_ resource.Resource                     = (*Resource)(nil)
	_ resource.ResourceWithConfigure        = (*Resource)(nil)
	_ resource.ResourceWithConfigValidators = (*Resource)(nil)
	_ resource.ResourceWithImportState      = (*Resource)(nil)
)

// Resource is the Terraform resource. The provider data must be a
// *clientset.ClientSet.
type Resource struct {
	client *wrap_things_service.WrapThingsServiceAPIService
	hooks  Hooks
}

// Hooks are handwritten steps around generated CRUD. Pass them to NewResource
// so a resource that is used without the overlay package does not silently skip them.
type Hooks struct {
	// BeforeWrite mutates the expanded request body before the API call.
	BeforeWrite func(context.Context, tfsdk.Config, any) diag.Diagnostics
	// AfterRead mutates state after flatten. prior is the plan after Create or
	// Update, or the state before Read.
	AfterRead func(context.Context, *tfsdk.State, any) diag.Diagnostics
}

// NewResource returns the resource. Use it in provider.Resources.
func NewResource(hooks Hooks) resource.Resource {
	return &Resource{hooks: hooks}
}

// NewResourceWithClient returns the resource with an injected API client.
func NewResourceWithClient(client *wrap_things_service.WrapThingsServiceAPIService, hooks Hooks) resource.Resource {
	return &Resource{client: client, hooks: hooks}
}

func (r *Resource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_" + TypeName
}

func (r *Resource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = Schema()
}

func (r *Resource) ConfigValidators(context.Context) []resource.ConfigValidator {
	return ConfigValidators()
}

func (r *Resource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return // The provider is not configured yet.
	}
	cs, ok := req.ProviderData.(*clientset.ClientSet)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data",
			fmt.Sprintf("The provider data is %T. The resource needs *clientset.ClientSet.", req.ProviderData))
		return
	}
	r.client = cs.WrapThings()
}

// ImportState sets the id. The Read after the import sets the other attributes.
func (r *Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func (r *Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.Append(validateCreate(ctx, req.Config, req.Plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var plan WrapThingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body, diags := expandCreate(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if r.hooks.BeforeWrite != nil {
		resp.Diagnostics.Append(r.hooks.BeforeWrite(ctx, req.Config, body)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}
	v, err := r.create(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Unable to create "+TypeName, err.Error())
		return
	}
	diags = r.setState(ctx, v, req.Plan, &resp.State)
	resp.Diagnostics.Append(diags...)
	if diags.HasError() && v != nil {
		// The resource exists, but the state is not complete. Keep the id, so
		// Terraform marks the resource as tainted and can delete it.
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), v.Id)...)
	}
}

// Read removes the resource from the state when the API does not find it.
func (r *Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	id, diags := stateID(ctx, req.State)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	v, err := r.get(ctx, id)
	if cxsdk.Code(err) == http.StatusNotFound {
		resp.Diagnostics.AddWarning("Resource disappeared during read",
			fmt.Sprintf("%s with id %v was not found. Terraform removed it from state.", TypeName, id))
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to read "+TypeName, fmt.Sprintf("id %v: %s", id, err))
		return
	}
	resp.Diagnostics.Append(r.setState(ctx, v, req.State, &resp.State)...)
}

// Update sends every Update field: a PUT replaces the resource. When no
// Update field changed, it sends no request and reads the resource instead
// (D14).
func (r *Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	id, diags := stateID(ctx, req.State)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body, diags := updateRequest(ctx, req.Config, req.Plan, req.State)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if body != nil && r.hooks.BeforeWrite != nil {
		resp.Diagnostics.Append(r.hooks.BeforeWrite(ctx, req.Config, body)...)
		if resp.Diagnostics.HasError() {
			return
		}
	}
	var v *wrap_things_service.WrapThing
	var err error
	if body == nil {
		v, err = r.get(ctx, id)
	} else {
		v, err = r.update(ctx, id, body)
	}
	if cxsdk.Code(err) == http.StatusNotFound {
		resp.Diagnostics.AddWarning("Resource disappeared during update",
			fmt.Sprintf("The API did not find %s with id %v. Terraform removed it from state.", TypeName, id))
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Unable to update "+TypeName, fmt.Sprintf("id %v: %s", id, err))
		return
	}
	resp.Diagnostics.Append(r.setState(ctx, v, req.Plan, &resp.State)...)
}

// Delete treats a resource that the API does not find as deleted.
func (r *Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	id, diags := stateID(ctx, req.State)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.delete(ctx, id)
	if err != nil && cxsdk.Code(err) != http.StatusNotFound {
		resp.Diagnostics.AddError("Unable to delete "+TypeName, fmt.Sprintf("id %v: %s", id, err))
	}
}

// The API calls. Each returns the error with its HTTP status and body.

func (r *Resource) create(ctx context.Context, body *wrap_things_service.CreateWrapThingRequest) (*wrap_things_service.WrapThing, error) {
	out, httpResp, err := r.client.WrapThingsServiceCreateWrapThing(ctx).CreateWrapThingRequest(*body).Execute()
	if err != nil {
		return nil, cxsdk.NewAPIError(httpResp, err)
	}
	if out == nil {
		return nil, nil
	}
	return out, nil
}

func (r *Resource) get(ctx context.Context, id string) (*wrap_things_service.WrapThing, error) {
	out, httpResp, err := r.client.WrapThingsServiceGetWrapThing(ctx, id).Execute()
	if err != nil {
		return nil, cxsdk.NewAPIError(httpResp, err)
	}
	if out == nil {
		return nil, nil
	}
	return out, nil
}

func (r *Resource) update(ctx context.Context, id string, body *wrap_things_service.ReplaceWrapThingRequest) (*wrap_things_service.WrapThing, error) {
	out, httpResp, err := r.client.WrapThingsServiceReplaceWrapThing(ctx, id).ReplaceWrapThingRequest(*body).Execute()
	if err != nil {
		return nil, cxsdk.NewAPIError(httpResp, err)
	}
	if out == nil {
		return nil, nil
	}
	return out, nil
}

func (r *Resource) delete(ctx context.Context, id string) error {
	_, httpResp, err := r.client.WrapThingsServiceDeleteWrapThing(ctx, id).Execute()
	return cxsdk.NewAPIError(httpResp, err)
}

// setState writes the resource in an API response to the state. A value that is empty in both
// the response and prior keeps its form from prior: the plan after Create or Update, or the
// state before Read. A state upgrade has no prior of this schema version, so it passes nil and
// the state takes the value of the API. flatten returns an error when the response has no
// resource.
func (r *Resource) setState(ctx context.Context, v *wrap_things_service.WrapThing, prior tfData, state *tfsdk.State) diag.Diagnostics {
	m, diags := flatten(ctx, v)
	if diags.HasError() {
		return diags
	}
	diags.Append(state.Set(ctx, m)...)
	if diags.HasError() {
		return diags
	}
	if prior != nil {
		diags.Append(keepPriorEmpty(ctx, prior, state)...)
	}
	if r.hooks.AfterRead != nil && !diags.HasError() {
		diags.Append(r.hooks.AfterRead(ctx, state, prior)...)
	}
	return diags
}

// Flatten returns the Terraform model of a resource in an API response, for a data source that
// uses the schema and the model of this resource. It has no prior model.
func Flatten(ctx context.Context, v *wrap_things_service.WrapThing) (*WrapThingModel, diag.Diagnostics) {
	return flatten(ctx, v)
}

// stateID returns the id in the state.
func stateID(ctx context.Context, state tfsdk.State) (string, diag.Diagnostics) {
	var id types.String
	diags := state.GetAttribute(ctx, path.Root("id"), &id)
	return id.ValueString(), diags
}
