// Copyright 2024 Coralogix Ltd.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: com/coralogixapis/dashboards/v1/common/group_limit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupByFields []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=group_by_fields,json=groupByFields,proto3" json:"group_by_fields,omitempty"`
	Limit         *wrapperspb.Int32Value    `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	MinPercentage *wrapperspb.Int32Value    `protobuf:"bytes,3,opt,name=min_percentage,json=minPercentage,proto3" json:"min_percentage,omitempty"`
}

func (x *GroupLimit) Reset() {
	*x = GroupLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_coralogixapis_dashboards_v1_common_group_limit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLimit) ProtoMessage() {}

func (x *GroupLimit) ProtoReflect() protoreflect.Message {
	mi := &file_com_coralogixapis_dashboards_v1_common_group_limit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLimit.ProtoReflect.Descriptor instead.
func (*GroupLimit) Descriptor() ([]byte, []int) {
	return file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescGZIP(), []int{0}
}

func (x *GroupLimit) GetGroupByFields() []*wrapperspb.StringValue {
	if x != nil {
		return x.GroupByFields
	}
	return nil
}

func (x *GroupLimit) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GroupLimit) GetMinPercentage() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinPercentage
	}
	return nil
}

var File_com_coralogixapis_dashboards_v1_common_group_limit_proto protoreflect.FileDescriptor

var file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDesc = []byte{
	0x0a, 0x38, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x72, 0x61, 0x6c, 0x6f, 0x67, 0x69, 0x78, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x64, 0x61,
	0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x44, 0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62, 0x79, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42,
	0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x6d, 0x69,
	0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0d, 0x6d, 0x69, 0x6e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescOnce sync.Once
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescData = file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDesc
)

func file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescGZIP() []byte {
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescOnce.Do(func() {
		file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescData)
	})
	return file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDescData
}

var file_com_coralogixapis_dashboards_v1_common_group_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_coralogixapis_dashboards_v1_common_group_limit_proto_goTypes = []any{
	(*GroupLimit)(nil),             // 0: com.coralogixapis.dashboards.v1.common.GroupLimit
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 2: google.protobuf.Int32Value
}
var file_com_coralogixapis_dashboards_v1_common_group_limit_proto_depIdxs = []int32{
	1, // 0: com.coralogixapis.dashboards.v1.common.GroupLimit.group_by_fields:type_name -> google.protobuf.StringValue
	2, // 1: com.coralogixapis.dashboards.v1.common.GroupLimit.limit:type_name -> google.protobuf.Int32Value
	2, // 2: com.coralogixapis.dashboards.v1.common.GroupLimit.min_percentage:type_name -> google.protobuf.Int32Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_com_coralogixapis_dashboards_v1_common_group_limit_proto_init() }
func file_com_coralogixapis_dashboards_v1_common_group_limit_proto_init() {
	if File_com_coralogixapis_dashboards_v1_common_group_limit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_coralogixapis_dashboards_v1_common_group_limit_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GroupLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_coralogixapis_dashboards_v1_common_group_limit_proto_goTypes,
		DependencyIndexes: file_com_coralogixapis_dashboards_v1_common_group_limit_proto_depIdxs,
		MessageInfos:      file_com_coralogixapis_dashboards_v1_common_group_limit_proto_msgTypes,
	}.Build()
	File_com_coralogixapis_dashboards_v1_common_group_limit_proto = out.File
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_rawDesc = nil
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_goTypes = nil
	file_com_coralogixapis_dashboards_v1_common_group_limit_proto_depIdxs = nil
}
