// Code generated by coralogix-iac-codegen v0.1.0-beta.7. DO NOT EDIT.

package configthing

import (
	"context"
	"fmt"
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"example.com/iac-test-sdk/go/openapi/gen/config_things_service"
)

// validateRequestValue accepts every planned value. An unknown value of a computed attribute is
// left out of the request, and the server supplies it, as the released resource did.
func validateRequestValue(_ path.Path, _, _ attr.Value, _ bool, _ *diag.Diagnostics) {}

var createFields = []struct {
	attr          string
	serverDefault bool
}{
	{attr: "name", serverDefault: false},
	{attr: "settings", serverDefault: false},
	{attr: "remotes", serverDefault: false},
}

func validateCreate(ctx context.Context, config, plan tfData) diag.Diagnostics {
	var diags diag.Diagnostics
	for _, field := range createFields {
		var c, p attr.Value
		var fieldDiags diag.Diagnostics
		fieldDiags.Append(config.GetAttribute(ctx, path.Root(field.attr), &c)...)
		fieldDiags.Append(plan.GetAttribute(ctx, path.Root(field.attr), &p)...)
		diags.Append(fieldDiags...)
		if fieldDiags.HasError() {
			continue
		}
		validateRequestValue(path.Root(field.attr), c, p, field.serverDefault, &diags)
	}
	return diags
}

// expandCreate returns the Create request body. A null value is not sent.
func expandCreate(ctx context.Context, m *ConfigThingModel) (*config_things_service.CreateConfigThingRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	out := expandCreateConfigThingRequest(ctx, path.Empty(), m, &diags)
	return out, diags
}

// expandUpdate returns the Update request body with every Update field. A
// null value is not sent, and the server clears it (a full replace).
func expandUpdate(ctx context.Context, m *ConfigThingModel) (*config_things_service.ReplaceConfigThingRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	out := expandReplaceConfigThingRequest(ctx, path.Empty(), m, &diags)
	return out, diags
}

// flatten returns the Terraform model of the resource in an API response.
// A value that the response does not have is null.
func flatten(ctx context.Context, v *config_things_service.ConfigThing, prior *ConfigThingModel) (*ConfigThingModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v == nil {
		diags.AddError("Missing resource", "The API response has no ConfigThing.")
		return nil, diags
	}
	out := flattenConfigThing(ctx, path.Empty(), v, prior, &diags)
	return out, diags
}

func expandCreateConfigThingRequest(ctx context.Context, p path.Path, m *ConfigThingModel, diags *diag.Diagnostics) *config_things_service.CreateConfigThingRequest {
	if m == nil {
		return nil
	}
	out := &config_things_service.CreateConfigThingRequest{}
	out.Name = expandString(m.Name)
	out.Settings = expandString(m.Settings)
	if items := expandElements[ConfigRemoteModel](ctx, p.AtName("remotes"), m.Remotes, diags); items != nil {
		out.Remotes = make([]config_things_service.ConfigRemote, 0, len(items))
		for i := range items {
			out.Remotes = append(out.Remotes, *expandConfigRemote(ctx, p.AtName("remotes").AtListIndex(i), &items[i], diags))
		}
	}
	return out
}

func expandConfigRemote(ctx context.Context, p path.Path, m *ConfigRemoteModel, diags *diag.Diagnostics) *config_things_service.ConfigRemote {
	if m == nil {
		return nil
	}
	out := &config_things_service.ConfigRemote{}
	out.Name = expandString(m.Name)
	out.RawConfiguration = expandString(m.RawConfiguration)
	return out
}

func flattenConfigRemote(ctx context.Context, p path.Path, v *config_things_service.ConfigRemote, prior *ConfigRemoteModel, diags *diag.Diagnostics) *ConfigRemoteModel {
	if v == nil {
		return nil
	}
	out := &ConfigRemoteModel{}
	out.Name = types.StringPointerValue(v.Name)
	out.RawConfiguration = types.StringPointerValue(v.RawConfiguration)
	if prior != nil {
		out.RawConfiguration = keepEquivalentText(prior.RawConfiguration, out.RawConfiguration, yamlEqual)
	}
	return out
}

func configRemoteAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":              types.StringType,
		"raw_configuration": types.StringType,
	}
}

func expandReplaceConfigThingRequest(ctx context.Context, p path.Path, m *ConfigThingModel, diags *diag.Diagnostics) *config_things_service.ReplaceConfigThingRequest {
	if m == nil {
		return nil
	}
	out := &config_things_service.ReplaceConfigThingRequest{}
	out.Name = expandString(m.Name)
	out.Settings = expandString(m.Settings)
	if items := expandElements[ConfigRemoteModel](ctx, p.AtName("remotes"), m.Remotes, diags); items != nil {
		out.Remotes = make([]config_things_service.ConfigRemote, 0, len(items))
		for i := range items {
			out.Remotes = append(out.Remotes, *expandConfigRemote(ctx, p.AtName("remotes").AtListIndex(i), &items[i], diags))
		}
	}
	return out
}

func flattenConfigThing(ctx context.Context, p path.Path, v *config_things_service.ConfigThing, prior *ConfigThingModel, diags *diag.Diagnostics) *ConfigThingModel {
	if v == nil {
		return nil
	}
	out := &ConfigThingModel{}
	out.Id = types.StringPointerValue(&v.Id)
	out.Name = types.StringPointerValue(v.Name)
	out.Settings = types.StringPointerValue(v.Settings)
	if prior != nil {
		out.Settings = keepEquivalentText(prior.Settings, out.Settings, jsonEqual)
	}
	out.Version = types.StringPointerValue(v.Version)
	out.Remotes = types.ListNull(types.ObjectType{AttrTypes: configRemoteAttrTypes()})
	if v.Remotes != nil {
		items := make([]ConfigRemoteModel, 0, len(v.Remotes))
		var priorRemotes []ConfigRemoteModel
		if prior != nil {
			priorRemotes = priorItems[ConfigRemoteModel](ctx, prior.Remotes)
		}
		for i := range v.Remotes {
			// The prior item at the same index keeps the order of its own lists and the text of its documents.
			var priorItem *ConfigRemoteModel
			if i < len(priorRemotes) {
				priorItem = &priorRemotes[i]
			}
			items = append(items, *flattenConfigRemote(ctx, p.AtName("remotes").AtListIndex(i), &v.Remotes[i], priorItem, diags))
		}
		out.Remotes = flattenList(ctx, types.ObjectType{AttrTypes: configRemoteAttrTypes()}, items, diags)
	}
	return out
}

// elements is a types.Set or a types.List.
type elements interface {
	IsNull() bool
	IsUnknown() bool
	ElementsAs(ctx context.Context, target interface{}, allowUnhandled bool) diag.Diagnostics
}

// expandElements returns the elements of v. It returns nil for a null
// value, and a non-nil slice for an empty value.
func expandElements[T any](ctx context.Context, p path.Path, v elements, diags *diag.Diagnostics) []T {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	out := []T{}
	for _, d := range v.ElementsAs(ctx, &out, false) {
		diags.Append(diag.WithPath(p, d))
	}
	if out == nil {
		out = []T{}
	}
	return out
}

func expandStrings[T ~string](ctx context.Context, p path.Path, v elements, diags *diag.Diagnostics) []T {
	items := expandElements[string](ctx, p, v, diags)
	if items == nil {
		return nil
	}
	out := make([]T, 0, len(items))
	for _, s := range items {
		out = append(out, T(s))
	}
	return out
}

// expandStringsSet preserves null and empty, and removes duplicate wire values.
func expandStringsSet[T ~string](ctx context.Context, p path.Path, v elements, diags *diag.Diagnostics) []T {
	items := expandStrings[T](ctx, p, v, diags)
	if items == nil {
		return nil
	}
	out := make([]T, 0, len(items))
	seen := make(map[T]struct{}, len(items))
	for _, item := range items {
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

// expandSet preserves null and empty, and removes duplicate scalar values.
func expandSet[T comparable](ctx context.Context, p path.Path, v elements, diags *diag.Diagnostics) []T {
	items := expandElements[T](ctx, p, v, diags)
	if items == nil {
		return nil
	}
	out := make([]T, 0, len(items))
	seen := make(map[T]struct{}, len(items))
	for _, item := range items {
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func expandString(v types.String) *string {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	s := v.ValueString()
	return &s
}

func expandBool(v types.Bool) *bool {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	b := v.ValueBool()
	return &b
}

func expandFloat64(v types.Float64) *float64 {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	f := v.ValueFloat64()
	return &f
}

func expandEnum[T ~string](v types.String) *T {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	e := T(v.ValueString())
	return &e
}

// expandUint64 returns the decimal string of v. The API sends 64-bit
// numbers as strings.
func expandUint64(p path.Path, v types.Int64, diags *diag.Diagnostics) *string {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	n := v.ValueInt64()
	if n < 0 {
		diags.AddAttributeError(p, "Invalid value", fmt.Sprintf("The value %d is negative. The API accepts only unsigned numbers.", n))
		return nil
	}
	s := strconv.FormatInt(n, 10)
	return &s
}

// flattenUint64 parses the decimal string of an unsigned 64-bit number. A
// value larger than the Terraform Int64 maximum is an error.
func flattenUint64(p path.Path, v *string, diags *diag.Diagnostics) types.Int64 {
	if v == nil {
		return types.Int64Null()
	}
	n, err := strconv.ParseUint(*v, 10, 64)
	if err != nil {
		diags.AddAttributeError(p, "Invalid API value", fmt.Sprintf("The API returned %q, which is not an unsigned number: %s", *v, err))
		return types.Int64Null()
	}
	if n > math.MaxInt64 {
		diags.AddAttributeError(p, "Invalid API value", fmt.Sprintf("The API returned %d, which is larger than the Terraform maximum %d.", n, int64(math.MaxInt64)))
		return types.Int64Null()
	}
	return types.Int64Value(int64(n))
}

func flattenEnum[T ~string](v *T, zero string) types.String {
	if v == nil || string(*v) == zero {
		return types.StringNull()
	}
	return types.StringValue(string(*v))
}

// priorItems returns the items of the prior list, or nil when it cannot be read. The prior only
// keeps an order or the text of a document, so a prior that cannot be read is not an error.
func priorItems[T any](ctx context.Context, v elements) []T {
	var scratch diag.Diagnostics
	items := expandElements[T](ctx, path.Empty(), v, &scratch)
	if scratch.HasError() {
		return nil
	}
	return items
}

func flattenTime(v *time.Time) types.String {
	if v == nil {
		return types.StringNull()
	}
	return types.StringValue(v.Format(time.RFC3339Nano))
}

func flattenStringsSet[T ~string](ctx context.Context, v []T, diags *diag.Diagnostics) types.Set {
	if v == nil {
		return types.SetNull(types.StringType)
	}
	return flattenSet(ctx, types.StringType, toStrings(v), diags)
}

func flattenStringsList[T ~string](ctx context.Context, v []T, diags *diag.Diagnostics) types.List {
	if v == nil {
		return types.ListNull(types.StringType)
	}
	return flattenList(ctx, types.StringType, toStrings(v), diags)
}

func invalidEnumElement(p path.Path, value, zero string, diags *diag.Diagnostics) {
	if value == zero {
		diags.AddAttributeError(p, "Invalid API enum value", fmt.Sprintf("The API returned protobuf zero enum value %q in a collection. The API must omit this element or return a concrete enum value.", value))
	}
}

func flattenEnumsSet[T ~string](ctx context.Context, p path.Path, v []T, zero string, diags *diag.Diagnostics) types.Set {
	if v == nil {
		return types.SetNull(types.StringType)
	}
	items := toStrings(v)
	sort.Strings(items)
	for _, value := range items {
		invalidEnumElement(p, value, zero, diags)
	}
	return flattenSet(ctx, types.StringType, items, diags)
}

func flattenEnumsList[T ~string](ctx context.Context, p path.Path, v []T, zero string, diags *diag.Diagnostics) types.List {
	if v == nil {
		return types.ListNull(types.StringType)
	}
	items := toStrings(v)
	for index, value := range items {
		invalidEnumElement(p.AtListIndex(index), value, zero, diags)
	}
	return flattenList(ctx, types.StringType, items, diags)
}

func toStrings[T ~string](v []T) []string {
	out := make([]string, 0, len(v))
	for _, s := range v {
		out = append(out, string(s))
	}
	return out
}

func flattenSet[T any](ctx context.Context, elem attr.Type, items []T, diags *diag.Diagnostics) types.Set {
	s, d := types.SetValueFrom(ctx, elem, items)
	diags.Append(d...)
	return s
}

func flattenList[T any](ctx context.Context, elem attr.Type, items []T, diags *diag.Diagnostics) types.List {
	l, d := types.ListValueFrom(ctx, elem, items)
	diags.Append(d...)
	return l
}
