// Code generated by coralogix-iac-codegen v0.1.0-beta.10. DO NOT EDIT.

package configthing

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ConfigThingModel struct {
	Id       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	Settings types.String `tfsdk:"settings"`
	Template types.String `tfsdk:"template"`
	Version  types.String `tfsdk:"version"`
	Remotes  types.List   `tfsdk:"remotes"`
	Labels   types.List   `tfsdk:"labels"`
	Metadata types.Map    `tfsdk:"metadata"`
}

type ConfigRemoteModel struct {
	Name             types.String `tfsdk:"name"`
	RawConfiguration types.String `tfsdk:"raw_configuration"`
}
