// Code generated by coralogix-iac-codegen v0.1.0-beta.6. DO NOT EDIT.

package configthing

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// Schema is the Terraform schema of the resource.
func Schema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				MarkdownDescription: "",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "",
			},
			"settings": schema.StringAttribute{
				Optional: true,
				PlanModifiers: []planmodifier.String{
					equivalentDocument{equal: jsonEqual},
				},
				MarkdownDescription: "A JSON object.",
			},
			"version": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "",
			},
			"remotes": schema.ListNestedAttribute{
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Optional:            true,
							MarkdownDescription: "",
						},
						"raw_configuration": schema.StringAttribute{
							Optional: true,
							PlanModifiers: []planmodifier.String{
								equivalentDocument{equal: yamlEqual},
							},
							MarkdownDescription: "A YAML document.",
						},
					},
				},
				MarkdownDescription: "",
			},
		},
	}
}

// ConfigValidators are the resource validators.
func ConfigValidators() []resource.ConfigValidator {
	return []resource.ConfigValidator{}
}
