/*
Configuration Group Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configuration_group_service

import (
	"bytes"
	"encoding/json"
)

var _ = bytes.MinRead

// checks if the ConfigurationFamilyCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationFamilyCreate{}

// ConfigurationFamilyCreate Initial configuration family to create.
type ConfigurationFamilyCreate struct {
	// Whether this family is active.
	Active *bool `json:"active,omitempty"`
	// Configuration family UUID v7 this family is based on.
	BasedOnConfigurationFamilyId *string `json:"basedOnConfigurationFamilyId,omitempty" validate:"regexp=^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"`
	// Collector semantic version this configuration family targets, without a leading v prefix. The service.version selector must match this value or is added automatically.
	CollectorVersion *string `json:"collectorVersion,omitempty" validate:"regexp=^(0|[1-9][0-9]*)\\\\.(0|[1-9][0-9]*)\\\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(?:\\\\.(?:0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\\\+([0-9A-Za-z-]+(?:\\\\.[0-9A-Za-z-]+)*))?$"`
	// Human-readable description.
	Description *string `json:"description,omitempty" validate:"regexp=^[\\s\\S]*$"`
	// Metadata stored with this configuration family.
	Metadata map[string]string `json:"metadata,omitempty"`
	// Remote configurations to create in this family.
	RemoteConfigurations []RemoteConfigurationCreate `json:"remoteConfigurations,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigurationFamilyCreate ConfigurationFamilyCreate

// NewConfigurationFamilyCreate instantiates a new ConfigurationFamilyCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationFamilyCreate() *ConfigurationFamilyCreate {
	this := ConfigurationFamilyCreate{}
	return &this
}

// NewConfigurationFamilyCreateWithDefaults instantiates a new ConfigurationFamilyCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationFamilyCreateWithDefaults() *ConfigurationFamilyCreate {
	this := ConfigurationFamilyCreate{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ConfigurationFamilyCreate) SetActive(v bool) {
	o.Active = &v
}

// GetBasedOnConfigurationFamilyId returns the BasedOnConfigurationFamilyId field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetBasedOnConfigurationFamilyId() string {
	if o == nil || IsNil(o.BasedOnConfigurationFamilyId) {
		var ret string
		return ret
	}
	return *o.BasedOnConfigurationFamilyId
}

// GetBasedOnConfigurationFamilyIdOk returns a tuple with the BasedOnConfigurationFamilyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetBasedOnConfigurationFamilyIdOk() (*string, bool) {
	if o == nil || IsNil(o.BasedOnConfigurationFamilyId) {
		return nil, false
	}
	return o.BasedOnConfigurationFamilyId, true
}

// HasBasedOnConfigurationFamilyId returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasBasedOnConfigurationFamilyId() bool {
	if o != nil && !IsNil(o.BasedOnConfigurationFamilyId) {
		return true
	}

	return false
}

// SetBasedOnConfigurationFamilyId gets a reference to the given string and assigns it to the BasedOnConfigurationFamilyId field.
func (o *ConfigurationFamilyCreate) SetBasedOnConfigurationFamilyId(v string) {
	o.BasedOnConfigurationFamilyId = &v
}

// GetCollectorVersion returns the CollectorVersion field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetCollectorVersion() string {
	if o == nil || IsNil(o.CollectorVersion) {
		var ret string
		return ret
	}
	return *o.CollectorVersion
}

// GetCollectorVersionOk returns a tuple with the CollectorVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetCollectorVersionOk() (*string, bool) {
	if o == nil || IsNil(o.CollectorVersion) {
		return nil, false
	}
	return o.CollectorVersion, true
}

// HasCollectorVersion returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasCollectorVersion() bool {
	if o != nil && !IsNil(o.CollectorVersion) {
		return true
	}

	return false
}

// SetCollectorVersion gets a reference to the given string and assigns it to the CollectorVersion field.
func (o *ConfigurationFamilyCreate) SetCollectorVersion(v string) {
	o.CollectorVersion = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ConfigurationFamilyCreate) SetDescription(v string) {
	o.Description = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]string{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ConfigurationFamilyCreate) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetRemoteConfigurations returns the RemoteConfigurations field value if set, zero value otherwise.
func (o *ConfigurationFamilyCreate) GetRemoteConfigurations() []RemoteConfigurationCreate {
	if o == nil || IsNil(o.RemoteConfigurations) {
		var ret []RemoteConfigurationCreate
		return ret
	}
	return o.RemoteConfigurations
}

// GetRemoteConfigurationsOk returns a tuple with the RemoteConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationFamilyCreate) GetRemoteConfigurationsOk() ([]RemoteConfigurationCreate, bool) {
	if o == nil || IsNil(o.RemoteConfigurations) {
		return nil, false
	}
	return o.RemoteConfigurations, true
}

// HasRemoteConfigurations returns a boolean if a field has been set.
func (o *ConfigurationFamilyCreate) HasRemoteConfigurations() bool {
	if o != nil && !IsNil(o.RemoteConfigurations) {
		return true
	}

	return false
}

// SetRemoteConfigurations gets a reference to the given []RemoteConfigurationCreate and assigns it to the RemoteConfigurations field.
func (o *ConfigurationFamilyCreate) SetRemoteConfigurations(v []RemoteConfigurationCreate) {
	o.RemoteConfigurations = v
}

func (o ConfigurationFamilyCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationFamilyCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.BasedOnConfigurationFamilyId) {
		toSerialize["basedOnConfigurationFamilyId"] = o.BasedOnConfigurationFamilyId
	}
	if !IsNil(o.CollectorVersion) {
		toSerialize["collectorVersion"] = o.CollectorVersion
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.RemoteConfigurations) {
		toSerialize["remoteConfigurations"] = o.RemoteConfigurations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigurationFamilyCreate) UnmarshalJSON(data []byte) (err error) {
	varConfigurationFamilyCreate := _ConfigurationFamilyCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varConfigurationFamilyCreate)

	if err != nil {
		return err
	}

	*o = ConfigurationFamilyCreate(varConfigurationFamilyCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "active")
		delete(additionalProperties, "basedOnConfigurationFamilyId")
		delete(additionalProperties, "collectorVersion")
		delete(additionalProperties, "description")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "remoteConfigurations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigurationFamilyCreate struct {
	value *ConfigurationFamilyCreate
	isSet bool
}

func (v NullableConfigurationFamilyCreate) Get() *ConfigurationFamilyCreate {
	return v.value
}

func (v *NullableConfigurationFamilyCreate) Set(val *ConfigurationFamilyCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationFamilyCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationFamilyCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationFamilyCreate(val *ConfigurationFamilyCreate) *NullableConfigurationFamilyCreate {
	return &NullableConfigurationFamilyCreate{value: val, isSet: true}
}

func (v NullableConfigurationFamilyCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationFamilyCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
