/*
Configuration Group Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configuration_group_service

import (
	"bytes"
	"encoding/json"
)

var _ = bytes.MinRead

// checks if the ConfigurationGroupServiceCreateConfigurationGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationGroupServiceCreateConfigurationGroupRequest{}

// ConfigurationGroupServiceCreateConfigurationGroupRequest Request to create a fleet-manager configuration group.
type ConfigurationGroupServiceCreateConfigurationGroupRequest struct {
	// Configuration group to create.
	Group                *ConfigurationGroupCreate `json:"group,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConfigurationGroupServiceCreateConfigurationGroupRequest ConfigurationGroupServiceCreateConfigurationGroupRequest

// NewConfigurationGroupServiceCreateConfigurationGroupRequest instantiates a new ConfigurationGroupServiceCreateConfigurationGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationGroupServiceCreateConfigurationGroupRequest() *ConfigurationGroupServiceCreateConfigurationGroupRequest {
	this := ConfigurationGroupServiceCreateConfigurationGroupRequest{}
	return &this
}

// NewConfigurationGroupServiceCreateConfigurationGroupRequestWithDefaults instantiates a new ConfigurationGroupServiceCreateConfigurationGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationGroupServiceCreateConfigurationGroupRequestWithDefaults() *ConfigurationGroupServiceCreateConfigurationGroupRequest {
	this := ConfigurationGroupServiceCreateConfigurationGroupRequest{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ConfigurationGroupServiceCreateConfigurationGroupRequest) GetGroup() ConfigurationGroupCreate {
	if o == nil || IsNil(o.Group) {
		var ret ConfigurationGroupCreate
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationGroupServiceCreateConfigurationGroupRequest) GetGroupOk() (*ConfigurationGroupCreate, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ConfigurationGroupServiceCreateConfigurationGroupRequest) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given ConfigurationGroupCreate and assigns it to the Group field.
func (o *ConfigurationGroupServiceCreateConfigurationGroupRequest) SetGroup(v ConfigurationGroupCreate) {
	o.Group = &v
}

func (o ConfigurationGroupServiceCreateConfigurationGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationGroupServiceCreateConfigurationGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigurationGroupServiceCreateConfigurationGroupRequest) UnmarshalJSON(data []byte) (err error) {
	varConfigurationGroupServiceCreateConfigurationGroupRequest := _ConfigurationGroupServiceCreateConfigurationGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varConfigurationGroupServiceCreateConfigurationGroupRequest)

	if err != nil {
		return err
	}

	*o = ConfigurationGroupServiceCreateConfigurationGroupRequest(varConfigurationGroupServiceCreateConfigurationGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigurationGroupServiceCreateConfigurationGroupRequest struct {
	value *ConfigurationGroupServiceCreateConfigurationGroupRequest
	isSet bool
}

func (v NullableConfigurationGroupServiceCreateConfigurationGroupRequest) Get() *ConfigurationGroupServiceCreateConfigurationGroupRequest {
	return v.value
}

func (v *NullableConfigurationGroupServiceCreateConfigurationGroupRequest) Set(val *ConfigurationGroupServiceCreateConfigurationGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationGroupServiceCreateConfigurationGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationGroupServiceCreateConfigurationGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationGroupServiceCreateConfigurationGroupRequest(val *ConfigurationGroupServiceCreateConfigurationGroupRequest) *NullableConfigurationGroupServiceCreateConfigurationGroupRequest {
	return &NullableConfigurationGroupServiceCreateConfigurationGroupRequest{value: val, isSet: true}
}

func (v NullableConfigurationGroupServiceCreateConfigurationGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationGroupServiceCreateConfigurationGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
