/*
Configuration Group Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configuration_group_service

import (
	"bytes"
	"encoding/json"
)

var _ = bytes.MinRead

// checks if the ReplaceConfigurationGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplaceConfigurationGroupResponse{}

// ReplaceConfigurationGroupResponse Response containing the updated fleet-manager configuration group.
type ReplaceConfigurationGroupResponse struct {
	// Updated configuration group.
	Group                *ConfigurationGroup `json:"group,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReplaceConfigurationGroupResponse ReplaceConfigurationGroupResponse

// NewReplaceConfigurationGroupResponse instantiates a new ReplaceConfigurationGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplaceConfigurationGroupResponse() *ReplaceConfigurationGroupResponse {
	this := ReplaceConfigurationGroupResponse{}
	return &this
}

// NewReplaceConfigurationGroupResponseWithDefaults instantiates a new ReplaceConfigurationGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplaceConfigurationGroupResponseWithDefaults() *ReplaceConfigurationGroupResponse {
	this := ReplaceConfigurationGroupResponse{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ReplaceConfigurationGroupResponse) GetGroup() ConfigurationGroup {
	if o == nil || IsNil(o.Group) {
		var ret ConfigurationGroup
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplaceConfigurationGroupResponse) GetGroupOk() (*ConfigurationGroup, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ReplaceConfigurationGroupResponse) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given ConfigurationGroup and assigns it to the Group field.
func (o *ReplaceConfigurationGroupResponse) SetGroup(v ConfigurationGroup) {
	o.Group = &v
}

func (o ReplaceConfigurationGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplaceConfigurationGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReplaceConfigurationGroupResponse) UnmarshalJSON(data []byte) (err error) {
	varReplaceConfigurationGroupResponse := _ReplaceConfigurationGroupResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varReplaceConfigurationGroupResponse)

	if err != nil {
		return err
	}

	*o = ReplaceConfigurationGroupResponse(varReplaceConfigurationGroupResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReplaceConfigurationGroupResponse struct {
	value *ReplaceConfigurationGroupResponse
	isSet bool
}

func (v NullableReplaceConfigurationGroupResponse) Get() *ReplaceConfigurationGroupResponse {
	return v.value
}

func (v *NullableReplaceConfigurationGroupResponse) Set(val *ReplaceConfigurationGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReplaceConfigurationGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReplaceConfigurationGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplaceConfigurationGroupResponse(val *ReplaceConfigurationGroupResponse) *NullableReplaceConfigurationGroupResponse {
	return &NullableReplaceConfigurationGroupResponse{value: val, isSet: true}
}

func (v NullableReplaceConfigurationGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplaceConfigurationGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
