name: tfsec
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  jobs:
  tfsec:
  name: tfsec
  runs-on: ubuntu-latest

  steps:
- name: Clone repo
  uses: actions/checkout@master
- name: tfsec
uses: aquasecurity/tfsec-action@v1.0.0